<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import
    Project="$(MSBuildExtensionsPath)/$(MSBuildToolsVersion)/Microsoft.Common.props"
    Condition="Exists('$(MSBuildExtensionsPath)/$(MSBuildToolsVersion)/Microsoft.Common.props')"
    />

  <PropertyGroup>
    <ProjectStyle>VS</ProjectStyle>
    <ChaosAnalyzers_CleanCode_Analyzer_TF>net4.5</ChaosAnalyzers_CleanCode_Analyzer_TF>
  </PropertyGroup>

  <Import Project="submodules/ChaosPresets.Targets/Frameworks/net4.5.2.targets" />
  <Import Project="submodules/ChaosPresets.Targets/Paths/Output/bin.targets" />
  <Import Project="ChaosFramework.IO.props" />

  <!-- Included Files -->
  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="source\**\*.cs" />
  </ItemGroup>

  <!-- References -->
  <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>

  <!-- Cleanup Task -->
  <Import Project="submodules/ChaosPresets.References/BuildTasks/ChaosBuild.ProjectAnalyzer.targets" />
  <Import Project="submodules/ChaosPresets.References/BuildTasks/ChaosBuild.CodeFormatter.Tasks.ChangedProjectFiles.targets" />

  <!-- Default Targets for Building CSharp Projects -->
  <Import Project="$(MSBuildToolsPath)/Microsoft.CSharp.targets" />
</Project>